### PR TITLE
Use Typography

### PR DESCRIPTION
**Pull request by mostlyfabulous**
Times New Roman is dead, long live Typography!

### CODE REVIEW

**Review by kikiho — APPROVED** [review]
i like it! 10/10 branch name
- approved by chief executive orang

**Review by ronan-f — APPROVED** [review]
Wow. Looking forward to this exciting change

**Review by thomasnakagawa — COMMENTED** [review]
Gotta agree, great font choice

**Comment by mostlyfabulous** [comment]
@dustxd Your font choice on point!

**Pull request merged**
